name: Backend CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout of the repository
        uses: actions/checkout@v3

      - name: Installing .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Setting up dependencies
        run: dotnet restore

      - name: Fix formatting issues
        run: dotnet format --severity info
        continue-on-error: true

      - name: Building
        run: dotnet build --configuration Release --no-restore
